### ISSUE TITLE
Table XML declaration: ROWS_LIMIT does not work

### ISSUE THREAD

**Issue by mantydze** [valdasraps/resthub#22]
Looks like that **1000** is hardcoded somewhere, because 
ROWS_LIMIT does not increase actual amount of rows returned from resthub.

Example: ROWS_LIMIT="5000" still returns 1000 rows

**Comment by valdasraps** [comment]
RH does not allow to have more than 1000 rows to be returned in one response:
https://github.com/valdasraps/resthub/blob/master/server/src/main/java/lt/emasina/resthub/server/query/Query.java#L109

**Comment by valdasraps** [comment]
Wont fix

**Comment by valdasraps** [comment]
Wont fix.
